workflows:
  deploy:
    name: Deploy Workflow

    schedules:
      - cron: "0 */2 * * *"
        trigger_on_push: false
        trigger_on_pull_request: false

    meta:
      abort_previous_builds: true

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true

    environment:
      node: "20"

    scripts:
      - name: Install Dependencies
        script: npm install

      - name: Start Project
        script: npm start

    artifacts:
      - "**/*.log"