Workflows:
  deploy:
    name: Deploy Workflow
    # ุงูุญูุงุธ ุนูู ุงูุญุฏ ุงูุฃูุตู ููุฏุฉ ุงูุจูุงุก 120 ุฏูููุฉ 
    # (ููู ุงูุญุฏ ุงูุฃูุตู ุงููุณููุญ ุจู ูู Codemagic).
    max_build_duration: 120
    
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          
      # ๐ ุฅุถุงูุฉ ูุณู ุงูุฌุฏููุฉ ูุฅุนุงุฏุฉ ุชุดุบูู ุงูุจูุงุก ูู ุณุงุนุชูู
      scheduling:
        - name: Periodic Deployment Restart
          # ุชุญุฏูุฏ ุงููุฑุน ุงููุฑุงุฏ ุจูุงุคู
          branch: master 
          # ุชุนุจูุฑ Cron ูุชุดุบูู ุงูุจูุงุก ูู ุงูุฏูููุฉ 0 ูู ูู ุณุงุนุชูู (* /2)
          cron: "0 */2 * * *" 

    environment:
      node: "20"

    scripts:
      - name: Install Dependencies
        script: npm install

      - name: Start Project
        # โ๏ธ ููุงุญุธุฉ: ูุฐุง ุงูุฃูุฑ (npm start) ุณูุนูู ูู Codemagic 
        # ุญุชู ูุตู ุงูุจูุงุก ุฅูู ุงููููุฉ ุงููุตูู (120 ุฏูููุฉ).
        script: npm start

    artifacts:
      - "**/*.log"
