workflows:
  deploy:
    name: Deploy Workflow

    # ๐ ุชู ุฅุฒุงูุฉ schedules (ูุฌุจ ุฅุนุฏุงุฏ ุงูุฌุฏููุฉ ูู ูุงุฌูุฉ ูุณุชุฎุฏู Codemagic ุฃู ุงูุจุญุซ ุนู ุทุฑููุฉ ุงูุชุถููู ุงูุตุญูุญุฉ)
    # ๐ ุชู ุฅุฒุงูุฉ meta (ูุฌุจ ุงูุจุญุซ ุนู ุงูุญูู ุงูุตุญูุญ ูู abort_previous_builds)

    # ๐ก ูุชู ุชูุนูู ูุฐุง ุงูุณูุฑ ุงูุนูู ุงูุชุฑุงุถููุง ุนูุฏ ุงูุฏูุน ูุงูุณุญุจ ุฅูู ุงููุฑูุน
    # ๐ก ูููู ุญุฐู ูุณู triggering ุฅุฐุง ููุช ุชุนุชูุฏ ุนูู ุงูุฅุนุฏุงุฏุงุช ุงูุงูุชุฑุงุถูุฉุ ุฃู ูุฌุจ ุงูุชุญูู ูู ุงููููุน ุงูุตุญูุญ ูู.

    environment:
      node: "20"

    scripts:
      - name: Install Dependencies
        script: npm install

      - name: Start Project
        script: npm start

    artifacts:
      - "**/artifacts.log" # ูุงุญุธ: ููุช ุจุชุบููุฑ **/*.log ุฅูู ** /artifacts.log ูููู ุดุงุฆุน

    # ูููู ุฅุถุงูุฉ ูุฐุง ุฅุฐุง ูุงู ูุฏุนูููุง ุจุงุณู ุญูู ุตุญูุญ
    # auto_cancel_builds: true
